blank_issues_enabled: false
contact_links:
  - name: "Join our Facebook Group"
    url: https://www.facebook.com/groups/129749737166432
    about: "Chat with fellow Downs lovers, share photos, and see what's happening"
  - name: "Report a problem on the Downs"
    url: https://www.cityoflondon.gov.uk/things-to-do/green-spaces/the-coulsdon-commons
    about: "For maintenance issues, contact the City of London directly"
